# awmaker - Abstracting Window Maker
#
# Fork of GNU Window Maker (GPL-2).
# Copyright (C) Rodolfo Garcia Penas (kix) <kix@kix.es>
# and individual contributors; see LICENSE for full attribution.
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# GNUmakefile — convenience targets for hosts without autotools (e.g. macOS).
#
# GNU make prefers this file over the automake-generated `Makefile`. It only
# special-cases the Docker targets; every other target (including the default
# `all`) is delegated to the autotools `Makefile` generated by ./configure, so
# the normal build on a Linux host — and the recursive `make` that
# script/docker-build.sh runs INSIDE the container — is unaffected.
#
# Why this exists: the containerised build (make docker) regenerates configure,
# Makefiles and build artifacts INSIDE Docker, so the host never needs a valid
# autotools Makefile for these targets. On macOS the host lacks automake/
# autoconf, so make must not try to rebuild the build system to reach `docker`.
#
# IMPORTANT: the default goal must stay `all` (delegated to the real Makefile),
# never `docker`. Otherwise the recursive `make` that runs inside the container
# would pick this file's `docker` target instead of building the tree.

.DEFAULT_GOAL := all

.PHONY: all docker docker-clean

all:
	$(MAKE) -f Makefile all

docker:
	./docker/build.sh

docker-clean:
	rm -rf build-libs
	git clean -fX

# Delegate every other target to the autotools-generated Makefile.
%:
	$(MAKE) -f Makefile $@
