#!/bin/sh
# awmaker - Abstracting Window Maker
#
# Fork of GNU Window Maker (GPL-2).
# Copyright (C) Rodolfo Garcia Penas (kix) <kix@kix.es>
# and individual contributors; see LICENSE for full attribution.
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Build and install the shared libraries (wrlib, WINGs) from the
# `third_party/wmaker-crm` submodule into the LOCAL `build-libs/` prefix.
#
# Everything stays inside the awmaker tree (build-libs/): nothing is installed
# into the system or the host. The `third_party/` submodule is never modified:
# we do an out-of-tree (VPATH) build, so all generated files land under
# build-libs/ as well.
#
# Strategy
#   * The libraries are configured from the submodule root (they have no
#     configure.ac of their own) but we only build the library directories
#     (wrlib, then WINGs) with `make -C`, not the rest of wmaker-crm.
#   * WINGs includes "GNUstep.h" (awmaker's src/GNUstep.h) from two files
#     (WINGs/wappresource.c, WINGs/wwindow.c), so we pass a CPPFLAGS include
#     path to the awmaker src directory.
#   * wmlib is NOT used by any awmaker binary, so it is skipped by default;
#     set BUILD_WMLIB=1 to build it too.
#
# Environment knobs:
#   LIBS_PREFIX   local prefix for the libraries (default: ./build-libs)
#   JOBS          parallelism (default: nproc)
#   BUILD_WMLIB   set to 1 to also build wmlib

set -e

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
SUBMODULE="$ROOT/third_party/wmaker-crm"
LIBS_PREFIX="${LIBS_PREFIX:-$ROOT/build-libs}"
JOBS="${JOBS:-$(nproc)}"
BUILD_WMLIB="${BUILD_WMLIB:-}"

if [ ! -d "$SUBMODULE/WINGs" ]; then
    echo "ERROR: wmaker-crm submodule is not initialised."
    echo "Run:  git submodule update --init third_party/wmaker-crm"
    exit 1
fi

echo "==> Shared libraries prefix (local, inside the tree): $LIBS_PREFIX"

# ---- Step 0: prepare out-of-tree build dir for the submodule ----------------
BUILD_DIR="$LIBS_PREFIX/wmaker-crm-build"
mkdir -p "$BUILD_DIR"

echo "==> Autotools bootstrap of the submodule (autoreconf)..."
(
    cd "$SUBMODULE"
    autoreconf -vfi -I m4
)

echo "==> Configuring the submodule (out-of-tree)..."
# Generate the library Makefiles from the submodule root configure. The
# CPPFLAGS include path makes awmaker's src/GNUstep.h available to WINGs.
(
    cd "$BUILD_DIR"
    "$SUBMODULE/configure" \
        --prefix="$LIBS_PREFIX" \
        --disable-silent-rules \
        CPPFLAGS="-I$ROOT/src" \
        LINGUAS=C

    # config-paths.h is normally generated by the submodule's top-level Makefile
    # rule (config-paths.h: Makefile), but we only descend into wrlib/WINGs with
    # `make -C`, so it is not produced automatically. Generate it here with the
    # same content. wrlib only uses LOCALEDIR; the rest is for completeness.
    echo "Generating config-paths.h"
    datadir="$LIBS_PREFIX/share"
    cat > config-paths.h <<CPE
/* this is a generated file - do not edit */
#define LOCALEDIR "$datadir/locale"
#define PIXMAPDIR "$datadir/pixmaps"
#define PKGDATADIR "$datadir/WindowMaker"
#define PKGCONFDIR "/etc/WindowMaker"
#define GSUSER_SUBDIR "GNUstep"
#define DEFAULTS_SUBDIR "Defaults"
#define USERDATA_SUBDIR "Library"
CPE
)

# ---- Step 1: wrlib ----------------------------------------------------------
echo "==> Building and installing wrlib..."
# INSTALL=install works around an automake VPATH quirk that otherwise produces
# a bogus "../0" install program when running `make -C <dir> install`.
(
    cd "$BUILD_DIR"
    make -C wrlib -j"$JOBS"
    make -C wrlib install INSTALL=install
)

# ---- Step 2: WINGs (links against the wrlib we just installed) --------------
echo "==> Building and installing WINGs (incl. WUtil)..."
(
    cd "$BUILD_DIR"
    make -C WINGs -j"$JOBS"
    make -C WINGs install INSTALL=install
)

if [ -n "$BUILD_WMLIB" ]; then
    echo "==> Building and installing wmlib..."
    (
        cd "$BUILD_DIR"
        make -C wmlib -j"$JOBS"
        make -C wmlib install INSTALL=install
    )
fi

echo "==> Done."
echo "    Libraries installed in: $LIBS_PREFIX"
echo "    (all local, nothing written outside the awmaker tree)"
echo "    For awmaker builds set: PKG_CONFIG_PATH=$LIBS_PREFIX/lib/pkgconfig"
